spring.application.name=jwt-nimbus-jose

## DATA SOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_jose
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

### JPA HIBERNATE

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false


## LOGBACK
logging.level.root=INFO
logging.level.com.github.igomarcelino.jwt_nimbus_jose=DEBUG
logging.level.org.springframework=warn
logging.level.org.hibernate=warn
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/jwt_nimbus_jose.log
logging.file.max-history=7